### ISSUE TITLE
seems that current db is out of date

### ISSUE THREAD

**Issue by meir-galilsoftware** [sosedoff/opentable#2]
How often the site database is updated?

**Comment by chelsea** [comment]
Hi Dan, any chance of getting the database updated? Looks like it's been quite a while if this issue is still open and places that I know are using open table aren't being found in searches.

I looked into just forking the repo and hosting it myself but I'm not part of the affiliate program so don't have access to download anything.

Cheers

**Comment by rjg88** [comment]
I also would love if you updated the database soon.

Thanks.

**Comment by sosedoff** [comment]
i dont know what to tell you guys, but OT has stopped updating affiliate data source. last update
to the XLS files was in mid-october 2014. even with that last update it looks like international
data was pulled from the source, only few countries are available right now. this is def a bad news
so i might just keep the current snapshot as is.
